# Generated by Django 3.2.5 on 2021-07-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTable',
            fields=[
                ('empid', models.AutoField(db_column='empid', primary_key=True, serialize=False)),
                ('empfirstname', models.CharField(db_column='empfirstname', max_length=100)),
                ('emplastname', models.CharField(db_column='emplastname', max_length=100)),
                ('empdob', models.DateTimeField(db_column='empdob')),
                ('status', models.CharField(db_column='status', max_length=100)),
            ],
            options={
                'db_table': 'EMPLOYE_RECORD',
            },
        ),
    ]
